

package com.google.googlejavaformat;

import com.google.common.base.MoreObjects;

/**
 * A {@code CloseOp} closes a level. It is an {@link Op} in the sequence of {@link Op}s generated by
 * {@link OpsBuilder}. When the sequence is turned into a {@link Doc} by {@link DocBuilder}, ranges
 * delimited by {@link OpenOp}-{@code CloseOp} pairs turn into nested {@link Doc.Level}s.
 */
public enum CloseOp implements Op {
    CLOSE;

    /**
     * Make a {@code CloseOp}, returning a singleton since they are all the same.
     *
     * @return the singleton {@code CloseOp}
     */
    public static Op make() {
        return CLOSE;
    }

    @Override
    public void add(DocBuilder builder) {
        builder.close();
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this).toString();
    }
}
